name: CD - Build and Deploy to AWS Lambda

on:
  pull_request:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC
      contents: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::225989356773:role/github-actions
        aws-region: us-east-2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install Dependencies
      run: npm install

    - name: Build for AWS Lambda
      run: npm run build_aws

    - name: Zip the Dist Folder
      run: |
        cd dist
        zip -r ../lambda_function.zip .

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name metricsPackage \
          --zip-file fileb://lambda_function.zip
